package com.sparrow.dao.model;

import java.util.Date;

public class SparrowThirdLoginInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_third_login_info.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_third_login_info.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_third_login_info.type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Byte type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_third_login_info.nickname
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_third_login_info.openid
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String openid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_third_login_info.unionid
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String unionid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_third_login_info.access_token
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String accessToken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_third_login_info.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_third_login_info.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date updateAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_third_login_info.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date deleteAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_third_login_info.id
	 * @return  the value of sparrow_third_login_info.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_third_login_info.id
	 * @param id  the value for sparrow_third_login_info.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_third_login_info.user_id
	 * @return  the value of sparrow_third_login_info.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_third_login_info.user_id
	 * @param userId  the value for sparrow_third_login_info.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_third_login_info.type
	 * @return  the value of sparrow_third_login_info.type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_third_login_info.type
	 * @param type  the value for sparrow_third_login_info.type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_third_login_info.nickname
	 * @return  the value of sparrow_third_login_info.nickname
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_third_login_info.nickname
	 * @param nickname  the value for sparrow_third_login_info.nickname
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_third_login_info.openid
	 * @return  the value of sparrow_third_login_info.openid
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getOpenid() {
		return openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_third_login_info.openid
	 * @param openid  the value for sparrow_third_login_info.openid
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setOpenid(String openid) {
		this.openid = openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_third_login_info.unionid
	 * @return  the value of sparrow_third_login_info.unionid
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getUnionid() {
		return unionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_third_login_info.unionid
	 * @param unionid  the value for sparrow_third_login_info.unionid
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUnionid(String unionid) {
		this.unionid = unionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_third_login_info.access_token
	 * @return  the value of sparrow_third_login_info.access_token
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getAccessToken() {
		return accessToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_third_login_info.access_token
	 * @param accessToken  the value for sparrow_third_login_info.access_token
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_third_login_info.created_at
	 * @return  the value of sparrow_third_login_info.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_third_login_info.created_at
	 * @param createdAt  the value for sparrow_third_login_info.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_third_login_info.update_at
	 * @return  the value of sparrow_third_login_info.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_third_login_info.update_at
	 * @param updateAt  the value for sparrow_third_login_info.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_third_login_info.delete_at
	 * @return  the value of sparrow_third_login_info.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getDeleteAt() {
		return deleteAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_third_login_info.delete_at
	 * @param deleteAt  the value for sparrow_third_login_info.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setDeleteAt(Date deleteAt) {
		this.deleteAt = deleteAt;
	}
}