package com.sparrow.dao.model;

import java.util.Date;

public class SparrowWorker {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_worker.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_worker.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_worker.name
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_worker.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_worker.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date updateAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_worker.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date deleteAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_worker.id
	 * @return  the value of sparrow_worker.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_worker.id
	 * @param id  the value for sparrow_worker.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_worker.user_id
	 * @return  the value of sparrow_worker.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_worker.user_id
	 * @param userId  the value for sparrow_worker.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_worker.name
	 * @return  the value of sparrow_worker.name
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_worker.name
	 * @param name  the value for sparrow_worker.name
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_worker.created_at
	 * @return  the value of sparrow_worker.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_worker.created_at
	 * @param createdAt  the value for sparrow_worker.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_worker.update_at
	 * @return  the value of sparrow_worker.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_worker.update_at
	 * @param updateAt  the value for sparrow_worker.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_worker.delete_at
	 * @return  the value of sparrow_worker.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getDeleteAt() {
		return deleteAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_worker.delete_at
	 * @param deleteAt  the value for sparrow_worker.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setDeleteAt(Date deleteAt) {
		this.deleteAt = deleteAt;
	}
}