package com.sparrow.dao.model;

import java.util.Date;

public class SparrowUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user.user_type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Byte userType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user.nickname
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user.user_mobile_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer userMobileId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user.salt
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String salt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user.login_pwd
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String loginPwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user.user_device_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer userDeviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user.status
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date updateAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date deleteAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user.last_login_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date lastLoginAt;
	
	private SparrowUserMobile userMobile;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user.id
	 * @return  the value of sparrow_user.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user.id
	 * @param id  the value for sparrow_user.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user.user_type
	 * @return  the value of sparrow_user.user_type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Byte getUserType() {
		return userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user.user_type
	 * @param userType  the value for sparrow_user.user_type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUserType(Byte userType) {
		this.userType = userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user.nickname
	 * @return  the value of sparrow_user.nickname
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user.nickname
	 * @param nickname  the value for sparrow_user.nickname
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user.user_mobile_id
	 * @return  the value of sparrow_user.user_mobile_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getUserMobileId() {
		return userMobileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user.user_mobile_id
	 * @param userMobileId  the value for sparrow_user.user_mobile_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUserMobileId(Integer userMobileId) {
		this.userMobileId = userMobileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user.salt
	 * @return  the value of sparrow_user.salt
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getSalt() {
		return salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user.salt
	 * @param salt  the value for sparrow_user.salt
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setSalt(String salt) {
		this.salt = salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user.login_pwd
	 * @return  the value of sparrow_user.login_pwd
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getLoginPwd() {
		return loginPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user.login_pwd
	 * @param loginPwd  the value for sparrow_user.login_pwd
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setLoginPwd(String loginPwd) {
		this.loginPwd = loginPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user.user_device_id
	 * @return  the value of sparrow_user.user_device_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getUserDeviceId() {
		return userDeviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user.user_device_id
	 * @param userDeviceId  the value for sparrow_user.user_device_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUserDeviceId(Integer userDeviceId) {
		this.userDeviceId = userDeviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user.status
	 * @return  the value of sparrow_user.status
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user.status
	 * @param status  the value for sparrow_user.status
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user.created_at
	 * @return  the value of sparrow_user.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user.created_at
	 * @param createdAt  the value for sparrow_user.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user.update_at
	 * @return  the value of sparrow_user.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user.update_at
	 * @param updateAt  the value for sparrow_user.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user.delete_at
	 * @return  the value of sparrow_user.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getDeleteAt() {
		return deleteAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user.delete_at
	 * @param deleteAt  the value for sparrow_user.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setDeleteAt(Date deleteAt) {
		this.deleteAt = deleteAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user.last_login_at
	 * @return  the value of sparrow_user.last_login_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getLastLoginAt() {
		return lastLoginAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user.last_login_at
	 * @param lastLoginAt  the value for sparrow_user.last_login_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setLastLoginAt(Date lastLoginAt) {
		this.lastLoginAt = lastLoginAt;
	}

	public SparrowUserMobile getUserMobile() {
		return userMobile;
	}

	public void setUserMobile(SparrowUserMobile userMobile) {
		this.userMobile = userMobile;
	}
}