package com.sparrow.dao.model;

import java.util.Date;

public class SparrowUserMobile {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_mobile.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_mobile.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_mobile.mobile
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_mobile.sim_no
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String simNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_mobile.mobile_uni
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String mobileUni;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_mobile.operation_name
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String operationName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_mobile.status
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_mobile.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_mobile.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date updateAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_mobile.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date deleteAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_mobile.id
	 * @return  the value of sparrow_user_mobile.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_mobile.id
	 * @param id  the value for sparrow_user_mobile.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_mobile.user_id
	 * @return  the value of sparrow_user_mobile.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_mobile.user_id
	 * @param userId  the value for sparrow_user_mobile.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_mobile.mobile
	 * @return  the value of sparrow_user_mobile.mobile
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_mobile.mobile
	 * @param mobile  the value for sparrow_user_mobile.mobile
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_mobile.sim_no
	 * @return  the value of sparrow_user_mobile.sim_no
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getSimNo() {
		return simNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_mobile.sim_no
	 * @param simNo  the value for sparrow_user_mobile.sim_no
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setSimNo(String simNo) {
		this.simNo = simNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_mobile.mobile_uni
	 * @return  the value of sparrow_user_mobile.mobile_uni
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getMobileUni() {
		return mobileUni;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_mobile.mobile_uni
	 * @param mobileUni  the value for sparrow_user_mobile.mobile_uni
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setMobileUni(String mobileUni) {
		this.mobileUni = mobileUni;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_mobile.operation_name
	 * @return  the value of sparrow_user_mobile.operation_name
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getOperationName() {
		return operationName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_mobile.operation_name
	 * @param operationName  the value for sparrow_user_mobile.operation_name
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setOperationName(String operationName) {
		this.operationName = operationName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_mobile.status
	 * @return  the value of sparrow_user_mobile.status
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_mobile.status
	 * @param status  the value for sparrow_user_mobile.status
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_mobile.created_at
	 * @return  the value of sparrow_user_mobile.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_mobile.created_at
	 * @param createdAt  the value for sparrow_user_mobile.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_mobile.update_at
	 * @return  the value of sparrow_user_mobile.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_mobile.update_at
	 * @param updateAt  the value for sparrow_user_mobile.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_mobile.delete_at
	 * @return  the value of sparrow_user_mobile.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getDeleteAt() {
		return deleteAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_mobile.delete_at
	 * @param deleteAt  the value for sparrow_user_mobile.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setDeleteAt(Date deleteAt) {
		this.deleteAt = deleteAt;
	}
}