package com.sparrow.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class SparrowLocation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_location.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_location.latitude
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private BigDecimal latitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_location.lengitude
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private BigDecimal lengitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_location.address
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_location.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_location.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date updateAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_location.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date deleteAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_location.id
	 * @return  the value of sparrow_location.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_location.id
	 * @param id  the value for sparrow_location.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_location.latitude
	 * @return  the value of sparrow_location.latitude
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public BigDecimal getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_location.latitude
	 * @param latitude  the value for sparrow_location.latitude
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_location.lengitude
	 * @return  the value of sparrow_location.lengitude
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public BigDecimal getLengitude() {
		return lengitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_location.lengitude
	 * @param lengitude  the value for sparrow_location.lengitude
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setLengitude(BigDecimal lengitude) {
		this.lengitude = lengitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_location.address
	 * @return  the value of sparrow_location.address
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_location.address
	 * @param address  the value for sparrow_location.address
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_location.created_at
	 * @return  the value of sparrow_location.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_location.created_at
	 * @param createdAt  the value for sparrow_location.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_location.update_at
	 * @return  the value of sparrow_location.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_location.update_at
	 * @param updateAt  the value for sparrow_location.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_location.delete_at
	 * @return  the value of sparrow_location.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getDeleteAt() {
		return deleteAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_location.delete_at
	 * @param deleteAt  the value for sparrow_location.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setDeleteAt(Date deleteAt) {
		this.deleteAt = deleteAt;
	}
}