package com.sparrow.dao.model;

import java.util.Date;

public class SparrowUserLoginInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_login_info.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_login_info.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_login_info.type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Byte type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_login_info.login_ip
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String loginIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_login_info.location_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer locationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_login_info.user_device_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer userDeviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_login_info.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_login_info.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date updateAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_login_info.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date deleteAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_login_info.id
	 * @return  the value of sparrow_user_login_info.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_login_info.id
	 * @param id  the value for sparrow_user_login_info.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_login_info.user_id
	 * @return  the value of sparrow_user_login_info.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_login_info.user_id
	 * @param userId  the value for sparrow_user_login_info.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_login_info.type
	 * @return  the value of sparrow_user_login_info.type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_login_info.type
	 * @param type  the value for sparrow_user_login_info.type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_login_info.login_ip
	 * @return  the value of sparrow_user_login_info.login_ip
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getLoginIp() {
		return loginIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_login_info.login_ip
	 * @param loginIp  the value for sparrow_user_login_info.login_ip
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_login_info.location_id
	 * @return  the value of sparrow_user_login_info.location_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getLocationId() {
		return locationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_login_info.location_id
	 * @param locationId  the value for sparrow_user_login_info.location_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_login_info.user_device_id
	 * @return  the value of sparrow_user_login_info.user_device_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getUserDeviceId() {
		return userDeviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_login_info.user_device_id
	 * @param userDeviceId  the value for sparrow_user_login_info.user_device_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUserDeviceId(Integer userDeviceId) {
		this.userDeviceId = userDeviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_login_info.created_at
	 * @return  the value of sparrow_user_login_info.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_login_info.created_at
	 * @param createdAt  the value for sparrow_user_login_info.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_login_info.update_at
	 * @return  the value of sparrow_user_login_info.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_login_info.update_at
	 * @param updateAt  the value for sparrow_user_login_info.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_login_info.delete_at
	 * @return  the value of sparrow_user_login_info.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getDeleteAt() {
		return deleteAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_login_info.delete_at
	 * @param deleteAt  the value for sparrow_user_login_info.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setDeleteAt(Date deleteAt) {
		this.deleteAt = deleteAt;
	}
}