package com.sparrow.dao.model;

import java.util.Date;

public class SparrowUserSearchCount {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search_count.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search_count.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search_count.type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Byte type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search_count.location_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer locationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search_count.count
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer count;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search_count.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search_count.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date updateAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search_count.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date deleteAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search_count.id
	 * @return  the value of sparrow_user_search_count.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search_count.id
	 * @param id  the value for sparrow_user_search_count.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search_count.user_id
	 * @return  the value of sparrow_user_search_count.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search_count.user_id
	 * @param userId  the value for sparrow_user_search_count.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search_count.type
	 * @return  the value of sparrow_user_search_count.type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search_count.type
	 * @param type  the value for sparrow_user_search_count.type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search_count.location_id
	 * @return  the value of sparrow_user_search_count.location_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getLocationId() {
		return locationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search_count.location_id
	 * @param locationId  the value for sparrow_user_search_count.location_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search_count.count
	 * @return  the value of sparrow_user_search_count.count
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getCount() {
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search_count.count
	 * @param count  the value for sparrow_user_search_count.count
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setCount(Integer count) {
		this.count = count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search_count.created_at
	 * @return  the value of sparrow_user_search_count.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search_count.created_at
	 * @param createdAt  the value for sparrow_user_search_count.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search_count.update_at
	 * @return  the value of sparrow_user_search_count.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search_count.update_at
	 * @param updateAt  the value for sparrow_user_search_count.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search_count.delete_at
	 * @return  the value of sparrow_user_search_count.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getDeleteAt() {
		return deleteAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search_count.delete_at
	 * @param deleteAt  the value for sparrow_user_search_count.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setDeleteAt(Date deleteAt) {
		this.deleteAt = deleteAt;
	}
}