package com.sparrow.dao.model;

import java.util.Date;

public class SparrowVersion {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_version.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_version.type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Byte type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_version.code
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_version.name
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_version.url
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_version.force_update
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Byte forceUpdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_version.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_version.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date updateAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_version.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date deleteAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_version.id
	 * @return  the value of sparrow_version.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_version.id
	 * @param id  the value for sparrow_version.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_version.type
	 * @return  the value of sparrow_version.type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_version.type
	 * @param type  the value for sparrow_version.type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_version.code
	 * @return  the value of sparrow_version.code
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_version.code
	 * @param code  the value for sparrow_version.code
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_version.name
	 * @return  the value of sparrow_version.name
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_version.name
	 * @param name  the value for sparrow_version.name
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_version.url
	 * @return  the value of sparrow_version.url
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_version.url
	 * @param url  the value for sparrow_version.url
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_version.force_update
	 * @return  the value of sparrow_version.force_update
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Byte getForceUpdate() {
		return forceUpdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_version.force_update
	 * @param forceUpdate  the value for sparrow_version.force_update
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setForceUpdate(Byte forceUpdate) {
		this.forceUpdate = forceUpdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_version.created_at
	 * @return  the value of sparrow_version.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_version.created_at
	 * @param createdAt  the value for sparrow_version.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_version.update_at
	 * @return  the value of sparrow_version.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_version.update_at
	 * @param updateAt  the value for sparrow_version.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_version.delete_at
	 * @return  the value of sparrow_version.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getDeleteAt() {
		return deleteAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_version.delete_at
	 * @param deleteAt  the value for sparrow_version.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setDeleteAt(Date deleteAt) {
		this.deleteAt = deleteAt;
	}
}