package com.sparrow.dao.model;

import java.util.Date;

public class SparrowUserDevice {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_device.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_device.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_device.device_type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Byte deviceType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_device.imei
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String imei;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_device.android_api
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String androidApi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_device.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_device.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date updateAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_device.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date deleteAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_device.id
	 * @return  the value of sparrow_user_device.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_device.id
	 * @param id  the value for sparrow_user_device.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_device.user_id
	 * @return  the value of sparrow_user_device.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_device.user_id
	 * @param userId  the value for sparrow_user_device.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_device.device_type
	 * @return  the value of sparrow_user_device.device_type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Byte getDeviceType() {
		return deviceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_device.device_type
	 * @param deviceType  the value for sparrow_user_device.device_type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setDeviceType(Byte deviceType) {
		this.deviceType = deviceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_device.imei
	 * @return  the value of sparrow_user_device.imei
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getImei() {
		return imei;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_device.imei
	 * @param imei  the value for sparrow_user_device.imei
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setImei(String imei) {
		this.imei = imei;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_device.android_api
	 * @return  the value of sparrow_user_device.android_api
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getAndroidApi() {
		return androidApi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_device.android_api
	 * @param androidApi  the value for sparrow_user_device.android_api
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setAndroidApi(String androidApi) {
		this.androidApi = androidApi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_device.created_at
	 * @return  the value of sparrow_user_device.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_device.created_at
	 * @param createdAt  the value for sparrow_user_device.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_device.update_at
	 * @return  the value of sparrow_user_device.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_device.update_at
	 * @param updateAt  the value for sparrow_user_device.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_device.delete_at
	 * @return  the value of sparrow_user_device.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getDeleteAt() {
		return deleteAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_device.delete_at
	 * @param deleteAt  the value for sparrow_user_device.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setDeleteAt(Date deleteAt) {
		this.deleteAt = deleteAt;
	}
}