package com.sparrow.dao.model;

import java.util.Date;

public class SparrowQuestionReview {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_question_review.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_question_review.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_question_review.question_type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer questionType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_question_review.content
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_question_review.reason_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer reasonId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_question_review.reason_other
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String reasonOther;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_question_review.operator_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer operatorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_question_review.operate_method
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Byte operateMethod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_question_review.status
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_question_review.operate_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date operateAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_question_review.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_question_review.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date updateAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_question_review.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date deleteAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_question_review.id
	 * @return  the value of sparrow_question_review.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_question_review.id
	 * @param id  the value for sparrow_question_review.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_question_review.user_id
	 * @return  the value of sparrow_question_review.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_question_review.user_id
	 * @param userId  the value for sparrow_question_review.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_question_review.question_type
	 * @return  the value of sparrow_question_review.question_type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getQuestionType() {
		return questionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_question_review.question_type
	 * @param questionType  the value for sparrow_question_review.question_type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setQuestionType(Integer questionType) {
		this.questionType = questionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_question_review.content
	 * @return  the value of sparrow_question_review.content
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_question_review.content
	 * @param content  the value for sparrow_question_review.content
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_question_review.reason_id
	 * @return  the value of sparrow_question_review.reason_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getReasonId() {
		return reasonId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_question_review.reason_id
	 * @param reasonId  the value for sparrow_question_review.reason_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setReasonId(Integer reasonId) {
		this.reasonId = reasonId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_question_review.reason_other
	 * @return  the value of sparrow_question_review.reason_other
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getReasonOther() {
		return reasonOther;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_question_review.reason_other
	 * @param reasonOther  the value for sparrow_question_review.reason_other
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setReasonOther(String reasonOther) {
		this.reasonOther = reasonOther;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_question_review.operator_id
	 * @return  the value of sparrow_question_review.operator_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getOperatorId() {
		return operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_question_review.operator_id
	 * @param operatorId  the value for sparrow_question_review.operator_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setOperatorId(Integer operatorId) {
		this.operatorId = operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_question_review.operate_method
	 * @return  the value of sparrow_question_review.operate_method
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Byte getOperateMethod() {
		return operateMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_question_review.operate_method
	 * @param operateMethod  the value for sparrow_question_review.operate_method
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setOperateMethod(Byte operateMethod) {
		this.operateMethod = operateMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_question_review.status
	 * @return  the value of sparrow_question_review.status
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_question_review.status
	 * @param status  the value for sparrow_question_review.status
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_question_review.operate_at
	 * @return  the value of sparrow_question_review.operate_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getOperateAt() {
		return operateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_question_review.operate_at
	 * @param operateAt  the value for sparrow_question_review.operate_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setOperateAt(Date operateAt) {
		this.operateAt = operateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_question_review.created_at
	 * @return  the value of sparrow_question_review.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_question_review.created_at
	 * @param createdAt  the value for sparrow_question_review.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_question_review.update_at
	 * @return  the value of sparrow_question_review.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_question_review.update_at
	 * @param updateAt  the value for sparrow_question_review.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_question_review.delete_at
	 * @return  the value of sparrow_question_review.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getDeleteAt() {
		return deleteAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_question_review.delete_at
	 * @param deleteAt  the value for sparrow_question_review.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setDeleteAt(Date deleteAt) {
		this.deleteAt = deleteAt;
	}
}