package com.sparrow.dao.model;

import java.util.Date;

public class SparrowUserSearchHotSpot {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search_hot_spot.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search_hot_spot.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search_hot_spot.type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search_hot_spot.object_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer objectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search_hot_spot.object_content
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String objectContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search_hot_spot.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search_hot_spot.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date updateAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search_hot_spot.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date deleteAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search_hot_spot.id
	 * @return  the value of sparrow_user_search_hot_spot.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search_hot_spot.id
	 * @param id  the value for sparrow_user_search_hot_spot.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search_hot_spot.user_id
	 * @return  the value of sparrow_user_search_hot_spot.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search_hot_spot.user_id
	 * @param userId  the value for sparrow_user_search_hot_spot.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search_hot_spot.type
	 * @return  the value of sparrow_user_search_hot_spot.type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search_hot_spot.type
	 * @param type  the value for sparrow_user_search_hot_spot.type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search_hot_spot.object_id
	 * @return  the value of sparrow_user_search_hot_spot.object_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getObjectId() {
		return objectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search_hot_spot.object_id
	 * @param objectId  the value for sparrow_user_search_hot_spot.object_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setObjectId(Integer objectId) {
		this.objectId = objectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search_hot_spot.object_content
	 * @return  the value of sparrow_user_search_hot_spot.object_content
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getObjectContent() {
		return objectContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search_hot_spot.object_content
	 * @param objectContent  the value for sparrow_user_search_hot_spot.object_content
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setObjectContent(String objectContent) {
		this.objectContent = objectContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search_hot_spot.created_at
	 * @return  the value of sparrow_user_search_hot_spot.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search_hot_spot.created_at
	 * @param createdAt  the value for sparrow_user_search_hot_spot.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search_hot_spot.update_at
	 * @return  the value of sparrow_user_search_hot_spot.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search_hot_spot.update_at
	 * @param updateAt  the value for sparrow_user_search_hot_spot.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search_hot_spot.delete_at
	 * @return  the value of sparrow_user_search_hot_spot.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getDeleteAt() {
		return deleteAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search_hot_spot.delete_at
	 * @param deleteAt  the value for sparrow_user_search_hot_spot.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setDeleteAt(Date deleteAt) {
		this.deleteAt = deleteAt;
	}
}