package com.sparrow.dao.model;

import java.util.Date;

public class SparrowUserShare {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_share.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_share.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_share.to_userid
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer toUserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_share.channel_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer channelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_share.type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_share.object_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer objectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_share.operation_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer operationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_share.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_share.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date updateAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_share.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date deleteAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_share.id
	 * @return  the value of sparrow_user_share.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_share.id
	 * @param id  the value for sparrow_user_share.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_share.user_id
	 * @return  the value of sparrow_user_share.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_share.user_id
	 * @param userId  the value for sparrow_user_share.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_share.to_userid
	 * @return  the value of sparrow_user_share.to_userid
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getToUserid() {
		return toUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_share.to_userid
	 * @param toUserid  the value for sparrow_user_share.to_userid
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setToUserid(Integer toUserid) {
		this.toUserid = toUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_share.channel_id
	 * @return  the value of sparrow_user_share.channel_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getChannelId() {
		return channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_share.channel_id
	 * @param channelId  the value for sparrow_user_share.channel_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setChannelId(Integer channelId) {
		this.channelId = channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_share.type
	 * @return  the value of sparrow_user_share.type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_share.type
	 * @param type  the value for sparrow_user_share.type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_share.object_id
	 * @return  the value of sparrow_user_share.object_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getObjectId() {
		return objectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_share.object_id
	 * @param objectId  the value for sparrow_user_share.object_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setObjectId(Integer objectId) {
		this.objectId = objectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_share.operation_id
	 * @return  the value of sparrow_user_share.operation_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getOperationId() {
		return operationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_share.operation_id
	 * @param operationId  the value for sparrow_user_share.operation_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setOperationId(Integer operationId) {
		this.operationId = operationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_share.created_at
	 * @return  the value of sparrow_user_share.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_share.created_at
	 * @param createdAt  the value for sparrow_user_share.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_share.update_at
	 * @return  the value of sparrow_user_share.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_share.update_at
	 * @param updateAt  the value for sparrow_user_share.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_share.delete_at
	 * @return  the value of sparrow_user_share.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getDeleteAt() {
		return deleteAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_share.delete_at
	 * @param deleteAt  the value for sparrow_user_share.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setDeleteAt(Date deleteAt) {
		this.deleteAt = deleteAt;
	}
}