package com.sparrow.dao.model;

import java.util.Date;

public class SparrowUserAddition {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_addition.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_addition.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_addition.home_address
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String homeAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_addition.work_address
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String workAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_addition.register_address
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String registerAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_addition.ip
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_addition.location_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer locationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_addition.last_login_ip
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String lastLoginIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_addition.last_location_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Long lastLocationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_addition.lock_remark
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String lockRemark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_addition.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_addition.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date updateAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_addition.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date deleteAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_addition.last_login_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date lastLoginAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_addition.id
	 * @return  the value of sparrow_user_addition.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_addition.id
	 * @param id  the value for sparrow_user_addition.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_addition.user_id
	 * @return  the value of sparrow_user_addition.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_addition.user_id
	 * @param userId  the value for sparrow_user_addition.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_addition.home_address
	 * @return  the value of sparrow_user_addition.home_address
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getHomeAddress() {
		return homeAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_addition.home_address
	 * @param homeAddress  the value for sparrow_user_addition.home_address
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setHomeAddress(String homeAddress) {
		this.homeAddress = homeAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_addition.work_address
	 * @return  the value of sparrow_user_addition.work_address
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getWorkAddress() {
		return workAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_addition.work_address
	 * @param workAddress  the value for sparrow_user_addition.work_address
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setWorkAddress(String workAddress) {
		this.workAddress = workAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_addition.register_address
	 * @return  the value of sparrow_user_addition.register_address
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getRegisterAddress() {
		return registerAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_addition.register_address
	 * @param registerAddress  the value for sparrow_user_addition.register_address
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setRegisterAddress(String registerAddress) {
		this.registerAddress = registerAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_addition.ip
	 * @return  the value of sparrow_user_addition.ip
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_addition.ip
	 * @param ip  the value for sparrow_user_addition.ip
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_addition.location_id
	 * @return  the value of sparrow_user_addition.location_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getLocationId() {
		return locationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_addition.location_id
	 * @param locationId  the value for sparrow_user_addition.location_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_addition.last_login_ip
	 * @return  the value of sparrow_user_addition.last_login_ip
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getLastLoginIp() {
		return lastLoginIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_addition.last_login_ip
	 * @param lastLoginIp  the value for sparrow_user_addition.last_login_ip
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setLastLoginIp(String lastLoginIp) {
		this.lastLoginIp = lastLoginIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_addition.last_location_id
	 * @return  the value of sparrow_user_addition.last_location_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Long getLastLocationId() {
		return lastLocationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_addition.last_location_id
	 * @param lastLocationId  the value for sparrow_user_addition.last_location_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setLastLocationId(Long lastLocationId) {
		this.lastLocationId = lastLocationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_addition.lock_remark
	 * @return  the value of sparrow_user_addition.lock_remark
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getLockRemark() {
		return lockRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_addition.lock_remark
	 * @param lockRemark  the value for sparrow_user_addition.lock_remark
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setLockRemark(String lockRemark) {
		this.lockRemark = lockRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_addition.created_at
	 * @return  the value of sparrow_user_addition.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_addition.created_at
	 * @param createdAt  the value for sparrow_user_addition.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_addition.update_at
	 * @return  the value of sparrow_user_addition.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_addition.update_at
	 * @param updateAt  the value for sparrow_user_addition.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_addition.delete_at
	 * @return  the value of sparrow_user_addition.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getDeleteAt() {
		return deleteAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_addition.delete_at
	 * @param deleteAt  the value for sparrow_user_addition.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setDeleteAt(Date deleteAt) {
		this.deleteAt = deleteAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_addition.last_login_at
	 * @return  the value of sparrow_user_addition.last_login_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getLastLoginAt() {
		return lastLoginAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_addition.last_login_at
	 * @param lastLoginAt  the value for sparrow_user_addition.last_login_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setLastLoginAt(Date lastLoginAt) {
		this.lastLoginAt = lastLoginAt;
	}
}