package com.sparrow.dao.model;

import java.util.Date;

public class SparrowContentClass {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_content_class.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_content_class.name
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_content_class.status
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_content_class.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_content_class.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date updateAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_content_class.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date deleteAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_content_class.id
	 * @return  the value of sparrow_content_class.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_content_class.id
	 * @param id  the value for sparrow_content_class.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_content_class.name
	 * @return  the value of sparrow_content_class.name
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_content_class.name
	 * @param name  the value for sparrow_content_class.name
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_content_class.status
	 * @return  the value of sparrow_content_class.status
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_content_class.status
	 * @param status  the value for sparrow_content_class.status
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_content_class.created_at
	 * @return  the value of sparrow_content_class.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_content_class.created_at
	 * @param createdAt  the value for sparrow_content_class.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_content_class.update_at
	 * @return  the value of sparrow_content_class.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_content_class.update_at
	 * @param updateAt  the value for sparrow_content_class.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_content_class.delete_at
	 * @return  the value of sparrow_content_class.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getDeleteAt() {
		return deleteAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_content_class.delete_at
	 * @param deleteAt  the value for sparrow_content_class.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setDeleteAt(Date deleteAt) {
		this.deleteAt = deleteAt;
	}
}