package com.sparrow.dao.model;

import java.util.Date;

public class SparrowUserSearch {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search.type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Byte type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search.content_class_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer contentClassId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search.content
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search.location_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer locationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search.ip
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search.share_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Integer shareId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date updateAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sparrow_user_search.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	private Date deleteAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search.id
	 * @return  the value of sparrow_user_search.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search.id
	 * @param id  the value for sparrow_user_search.id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search.user_id
	 * @return  the value of sparrow_user_search.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search.user_id
	 * @param userId  the value for sparrow_user_search.user_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search.type
	 * @return  the value of sparrow_user_search.type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search.type
	 * @param type  the value for sparrow_user_search.type
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search.content_class_id
	 * @return  the value of sparrow_user_search.content_class_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getContentClassId() {
		return contentClassId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search.content_class_id
	 * @param contentClassId  the value for sparrow_user_search.content_class_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setContentClassId(Integer contentClassId) {
		this.contentClassId = contentClassId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search.content
	 * @return  the value of sparrow_user_search.content
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search.content
	 * @param content  the value for sparrow_user_search.content
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search.location_id
	 * @return  the value of sparrow_user_search.location_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getLocationId() {
		return locationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search.location_id
	 * @param locationId  the value for sparrow_user_search.location_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search.ip
	 * @return  the value of sparrow_user_search.ip
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search.ip
	 * @param ip  the value for sparrow_user_search.ip
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search.share_id
	 * @return  the value of sparrow_user_search.share_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Integer getShareId() {
		return shareId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search.share_id
	 * @param shareId  the value for sparrow_user_search.share_id
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setShareId(Integer shareId) {
		this.shareId = shareId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search.created_at
	 * @return  the value of sparrow_user_search.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search.created_at
	 * @param createdAt  the value for sparrow_user_search.created_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search.update_at
	 * @return  the value of sparrow_user_search.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search.update_at
	 * @param updateAt  the value for sparrow_user_search.update_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sparrow_user_search.delete_at
	 * @return  the value of sparrow_user_search.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public Date getDeleteAt() {
		return deleteAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sparrow_user_search.delete_at
	 * @param deleteAt  the value for sparrow_user_search.delete_at
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	public void setDeleteAt(Date deleteAt) {
		this.deleteAt = deleteAt;
	}
}