package com.sparrow.dao.mapper;

import com.sparrow.dao.model.SparrowVersion;

public interface SparrowVersionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_version
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_version
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insert(SparrowVersion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_version
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insertSelective(SparrowVersion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_version
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	SparrowVersion selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_version
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKeySelective(SparrowVersion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_version
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKey(SparrowVersion record);
}