package com.sparrow.dao.mapper;

import com.sparrow.dao.model.SparrowUserDevice;

public interface SparrowUserDeviceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_device
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_device
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insert(SparrowUserDevice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_device
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insertSelective(SparrowUserDevice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_device
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	SparrowUserDevice selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_device
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKeySelective(SparrowUserDevice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_device
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKey(SparrowUserDevice record);
}