package com.sparrow.dao.mapper;

import com.sparrow.dao.model.SparrowWorker;

public interface SparrowWorkerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_worker
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_worker
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insert(SparrowWorker record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_worker
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insertSelective(SparrowWorker record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_worker
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	SparrowWorker selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_worker
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKeySelective(SparrowWorker record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_worker
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKey(SparrowWorker record);
}