package com.sparrow.dao.mapper;

import com.sparrow.dao.model.SparrowThirdLoginInfo;

public interface SparrowThirdLoginInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_third_login_info
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_third_login_info
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insert(SparrowThirdLoginInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_third_login_info
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insertSelective(SparrowThirdLoginInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_third_login_info
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	SparrowThirdLoginInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_third_login_info
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKeySelective(SparrowThirdLoginInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_third_login_info
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKey(SparrowThirdLoginInfo record);
}