package com.sparrow.dao.mapper;

import com.sparrow.dao.model.SparrowUserLoginInfo;

public interface SparrowUserLoginInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_login_info
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_login_info
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insert(SparrowUserLoginInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_login_info
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insertSelective(SparrowUserLoginInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_login_info
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	SparrowUserLoginInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_login_info
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKeySelective(SparrowUserLoginInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_login_info
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKey(SparrowUserLoginInfo record);
}