package com.sparrow.dao.mapper;

import org.apache.ibatis.annotations.Param;

import com.sparrow.dao.model.SparrowUser;

public interface SparrowUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insert(SparrowUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insertSelective(SparrowUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	SparrowUser selectByPrimaryKey(@Param("id")Integer id, @Param("method")Integer method);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	SparrowUser selectByName(@Param("nickname")String nickname, @Param("method")Integer method);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	SparrowUser selectByMobile(@Param("mobile")String mobile, @Param("method")Integer method);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKeySelective(SparrowUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKey(SparrowUser record);
}