package com.sparrow.dao.mapper;

import com.sparrow.dao.model.SparrowContentClass;

public interface SparrowContentClassMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_content_class
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_content_class
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insert(SparrowContentClass record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_content_class
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insertSelective(SparrowContentClass record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_content_class
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	SparrowContentClass selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_content_class
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKeySelective(SparrowContentClass record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_content_class
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKey(SparrowContentClass record);
}