package com.sparrow.dao.mapper;

import com.sparrow.dao.model.SparrowUserAddition;

public interface SparrowUserAdditionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_addition
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_addition
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insert(SparrowUserAddition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_addition
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insertSelective(SparrowUserAddition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_addition
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	SparrowUserAddition selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_addition
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKeySelective(SparrowUserAddition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_addition
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKey(SparrowUserAddition record);
}