package com.sparrow.dao.mapper;

import com.sparrow.dao.model.SparrowShareChannel;

public interface SparrowShareChannelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_share_channel
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_share_channel
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insert(SparrowShareChannel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_share_channel
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insertSelective(SparrowShareChannel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_share_channel
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	SparrowShareChannel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_share_channel
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKeySelective(SparrowShareChannel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_share_channel
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKey(SparrowShareChannel record);
}