package com.sparrow.dao.mapper;

import com.sparrow.dao.model.SparrowUserMobile;

public interface SparrowUserMobileMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_mobile
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_mobile
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insert(SparrowUserMobile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_mobile
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insertSelective(SparrowUserMobile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_mobile
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	SparrowUserMobile selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_mobile
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKeySelective(SparrowUserMobile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_mobile
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKey(SparrowUserMobile record);
}