package com.sparrow.dao.mapper;

import com.sparrow.dao.model.SparrowUserSearchHotSpot;

public interface SparrowUserSearchHotSpotMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_search_hot_spot
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_search_hot_spot
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insert(SparrowUserSearchHotSpot record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_search_hot_spot
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insertSelective(SparrowUserSearchHotSpot record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_search_hot_spot
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	SparrowUserSearchHotSpot selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_search_hot_spot
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKeySelective(SparrowUserSearchHotSpot record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_search_hot_spot
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKey(SparrowUserSearchHotSpot record);
}