package com.sparrow.dao.mapper;

import com.sparrow.dao.model.SparrowUserInfo;

public interface SparrowUserInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_info
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_info
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insert(SparrowUserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_info
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insertSelective(SparrowUserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_info
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	SparrowUserInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_info
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKeySelective(SparrowUserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_info
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKey(SparrowUserInfo record);
}