package com.sparrow.dao.mapper;

import com.sparrow.dao.model.SparrowUserOperation;

public interface SparrowUserOperationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_operation
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_operation
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insert(SparrowUserOperation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_operation
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insertSelective(SparrowUserOperation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_operation
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	SparrowUserOperation selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_operation
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKeySelective(SparrowUserOperation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_operation
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKey(SparrowUserOperation record);
}