package com.sparrow.dao.mapper;

import com.sparrow.dao.model.SparrowUserShare;

public interface SparrowUserShareMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_share
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_share
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insert(SparrowUserShare record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_share
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insertSelective(SparrowUserShare record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_share
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	SparrowUserShare selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_share
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKeySelective(SparrowUserShare record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_share
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKey(SparrowUserShare record);
}