package com.sparrow.dao.mapper;

import com.sparrow.dao.model.SparrowLocation;

public interface SparrowLocationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_location
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_location
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insert(SparrowLocation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_location
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insertSelective(SparrowLocation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_location
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	SparrowLocation selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_location
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKeySelective(SparrowLocation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_location
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKey(SparrowLocation record);
}