package com.sparrow.dao.mapper;

import com.sparrow.dao.model.SparrowTest;

public interface SparrowTestMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_test
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_test
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insert(SparrowTest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_test
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insertSelective(SparrowTest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_test
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	SparrowTest selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_test
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKeySelective(SparrowTest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_test
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKey(SparrowTest record);
}