package com.sparrow.dao.mapper;

import com.sparrow.dao.model.SparrowUserSearchCount;

public interface SparrowUserSearchCountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_search_count
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_search_count
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insert(SparrowUserSearchCount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_search_count
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int insertSelective(SparrowUserSearchCount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_search_count
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	SparrowUserSearchCount selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_search_count
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKeySelective(SparrowUserSearchCount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sparrow_user_search_count
	 * @mbg.generated  Sat Sep 02 11:40:28 CST 2017
	 */
	int updateByPrimaryKey(SparrowUserSearchCount record);
}